/* __PROMPT_HUB_LEGACY_SPLIT_LOADER__ admin.js
 * Generated by scripts/create-legacy-runtime-split.mjs.
 * The runtime still executes synchronously so downstream classic scripts keep
 * the same ordering and closure behavior as the former monolithic file.
 */
(function () {
  'use strict';
  var parts = [
    "legacy/admin/part-01.js",
    "legacy/admin/part-02.js",
    "legacy/admin/part-03.js",
    "legacy/admin/part-04.js",
    "legacy/admin/part-05.js",
    "legacy/admin/part-06.js"
  ];
  var current = document.currentScript;
  var baseUrl = current && current.src ? current.src : 'admin.js';
  var version = (baseUrl.match(/[?&]v=([^&]+)/) || [])[1] || window.__APP_BUILD__ || String(Date.now());
  // 首屏并行预取：index.html 在解析期已用 fetch 并行取走这些分片并缓存文本，
  // 命中时直接取用，未命中才退回同步 XHR —— 把 N 个串行阻塞 RTT 压成 1 次并行等待。
  var store = window.__PH_PART_STORE__;
  var code = '';
  for (var i = 0; i < parts.length; i += 1) {
    var chunk = store && store.text ? store.text.get(parts[i]) : null;
    if (chunk == null) {
      var url = new URL(parts[i] + '?v=' + encodeURIComponent(version), baseUrl).href;
      var xhr = new XMLHttpRequest();
      xhr.open('GET', url, false);
      xhr.send(null);
      if ((xhr.status && (xhr.status < 200 || xhr.status >= 300)) || !xhr.responseText) {
        throw new Error('Failed to load admin.js chunk: ' + parts[i] + ' (' + xhr.status + ')');
      }
      chunk = xhr.responseText;
    }
    code += chunk + '\n';
  }
  (0, eval)(code + '\n//# sourceURL=admin.js.legacy-runtime.js');
})();
