/**
 * Custom API domain - generated by setup-custom-domain.ps1
 */
window.CUSTOM_API_HOST = 'api.prompt-hub.cn';
window.CUSTOM_PAGES_ORIGINS = ['https://prompt-hub-hub.pages.dev', 'https://prompt-hub-web.pages.dev'];