/* __PROMPT_HUB_LEGACY_SPLIT_LOADER__ features-draft.js
 * Generated by scripts/create-legacy-runtime-split.mjs.
 * The runtime still executes synchronously so downstream classic scripts keep
 * the same ordering and closure behavior as the former monolithic file.
 */
(function () {
  'use strict';
  var parts = [
    "legacy/features-draft/part-01.js",
    "legacy/features-draft/part-02.js",
    "legacy/features-draft/part-03.js",
    "legacy/features-draft/part-04.js",
    "legacy/features-draft/part-05.js",
    "legacy/features-draft/part-06.js",
    "legacy/features-draft/part-07.js",
    "legacy/features-draft/part-08.js",
    "legacy/features-draft/part-09.js",
    "legacy/features-draft/part-10.js",
    "legacy/features-draft/part-11.js",
    "legacy/features-draft/part-12.js",
    "legacy/features-draft/part-13.js"
  ];
  var current = document.currentScript;
  var baseUrl = current && current.src ? current.src : 'features-draft.js';
  var version = (baseUrl.match(/[?&]v=([^&]+)/) || [])[1] || window.__APP_BUILD__ || String(Date.now());
  var code = '';
  for (var i = 0; i < parts.length; i += 1) {
    var url = new URL(parts[i] + '?v=' + encodeURIComponent(version), baseUrl).href;
    var xhr = new XMLHttpRequest();
    xhr.open('GET', url, false);
    xhr.send(null);
    if ((xhr.status && (xhr.status < 200 || xhr.status >= 300)) || !xhr.responseText) {
      throw new Error('Failed to load features-draft.js chunk: ' + parts[i] + ' (' + xhr.status + ')');
    }
    code += xhr.responseText + '\n';
  }
  (0, eval)(code + '\n//# sourceURL=features-draft.js.legacy-runtime.js');
})();
