/* __PROMPT_HUB_LEGACY_SPLIT_LOADER__ features-assets.js
 * Generated by scripts/create-legacy-runtime-split.mjs.
 * The runtime still executes synchronously so downstream classic scripts keep
 * the same ordering and closure behavior as the former monolithic file.
 */
(function () {
  'use strict';
  var parts = [
    "legacy/features-assets/part-01.js",
    "legacy/features-assets/part-02.js",
    "legacy/features-assets/part-03.js",
    "legacy/features-assets/part-04.js",
    "legacy/features-assets/part-05.js"
  ];
  var current = document.currentScript;
  var baseUrl = current && current.src ? current.src : 'features-assets.js';
  var version = (baseUrl.match(/[?&]v=([^&]+)/) || [])[1] || window.__APP_BUILD__ || String(Date.now());
  var code = '';
  for (var i = 0; i < parts.length; i += 1) {
    var url = new URL(parts[i] + '?v=' + encodeURIComponent(version), baseUrl).href;
    var xhr = new XMLHttpRequest();
    xhr.open('GET', url, false);
    xhr.send(null);
    if ((xhr.status && (xhr.status < 200 || xhr.status >= 300)) || !xhr.responseText) {
      throw new Error('Failed to load features-assets.js chunk: ' + parts[i] + ' (' + xhr.status + ')');
    }
    code += xhr.responseText + '\n';
  }
  (0, eval)(code + '\n//# sourceURL=features-assets.js.legacy-runtime.js');
})();
