# Bind custom API domain to Worker + update frontend api-domain.config.js
param(
  [Parameter(Mandatory = $true)]
  [string]$ApiHost,
  [string]$PagesOrigin = "",
  [switch]$Deploy
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$apiDomainFile = Join-Path $root "api-domain.config.js"
$wranglerFile = Join-Path $PSScriptRoot "wrangler.toml"

$ApiHost = $ApiHost.Trim().ToLower() -replace '^https?://', '' -replace '/$', ''
if ($ApiHost -notmatch '^[a-z0-9]([a-z0-9.-]*[a-z0-9])?$') {
  Write-Error "Invalid ApiHost: $ApiHost"
}

$pagesList = @()
if ($PagesOrigin) {
  $p = $PagesOrigin.Trim()
  if ($p -notmatch '^https?://') { $p = 'https://' + $p }
  $pagesList += $p.TrimEnd('/')
}
$pagesList += @(
  'https://prompt-hub-hub.pages.dev',
  'https://prompt-hub-web.pages.dev'
)
$pagesList = $pagesList | Select-Object -Unique
$corsLine = ($pagesList -join ',')

$apiJs = @"
/**
 * Custom API domain - generated by setup-custom-domain.ps1
 */
window.CUSTOM_API_HOST = '$ApiHost';
window.CUSTOM_PAGES_ORIGINS = [$(
  ($pagesList | ForEach-Object { "'$_'" }) -join ', '
)];
"@
[System.IO.File]::WriteAllText($apiDomainFile, $apiJs, [System.Text.UTF8Encoding]::new($false))
Write-Host "Updated: $apiDomainFile" -ForegroundColor Green

$toml = Get-Content $wranglerFile -Raw -Encoding UTF8
$toml = $toml -replace '(?m)^\[\[routes\]\].*?(?=^\[|\z)', ''
$toml = $toml -replace '(?m)^CORS_ORIGINS = .*', "CORS_ORIGINS = `"$corsLine`""
if ($toml -notmatch '\[\[routes\]\]') {
  $routeBlock = @"

[[routes]]
pattern = "$ApiHost"
custom_domain = true

"@
  $toml = $toml -replace '(\[observability\])', "$routeBlock`$1"
}
[System.IO.File]::WriteAllText($wranglerFile, $toml, [System.Text.UTF8Encoding]::new($false))
Write-Host "Updated: $wranglerFile (CORS + route $ApiHost)" -ForegroundColor Green

Write-Host ""
Write-Host "=== You must do in Cloudflare Dashboard ===" -ForegroundColor Cyan
Write-Host "1. Domain added to this Cloudflare account (buy or transfer)"
Write-Host "2. Workers -> prompt-hub-api -> may auto-create DNS after deploy"
Write-Host "3. Test: https://$ApiHost/health"
Write-Host "4. Redeploy Pages (git push or pack-deploy.zip) so api-domain.config.js is live"
Write-Host ""

if ($Deploy) {
  if (-not (Test-Path (Join-Path $PSScriptRoot "node_modules\wrangler"))) {
    npm install
  }
  npm run deploy
  Write-Host "Worker deployed. Open https://$ApiHost/health"
}
